version: '3.9'

services:

  # Spin up 3 database nodes

  codsworth1:
    image: cockroachdb/cockroach:v23.1.11
    container_name: codsworth1
    hostname: codsworth1
    networks:
      - codsworthnet
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - codsworth1:/cockroach/cockroach-data
    command: start --advertise-addr=codsworth1:26357 --http-addr=codsworth1:8080 --listen-addr=codsworth1:26357 --sql-addr=codsworth1:26257 --insecure --join=codsworth1:26357,codsworth2:26357,codsworth3:26357

  codsworth2:
    image: cockroachdb/cockroach:v23.1.11
    container_name: codsworth2
    hostname: codsworth2
    networks:
      - codsworthnet
    ports:
      - "26258:26258"
      - "8081:8081"
    volumes:
      - codsworth2:/cockroach/cockroach-data
    command: start --advertise-addr=codsworth2:26357 --http-addr=codsworth2:8081 --listen-addr=codsworth2:26357 --sql-addr=codsworth2:26258 --insecure --join=codsworth1:26357,codsworth2:26357,codsworth3:26357

  codsworth3:
    image: cockroachdb/cockroach:v23.1.11
    container_name: codsworth3
    hostname: codsworth3
    networks:
      - codsworthnet
    ports:
      - "26259:26259"
      - "8082:8082"
    volumes:
      - codsworth3:/cockroach/cockroach-data
    command: start --advertise-addr=codsworth3:26357 --http-addr=codsworth3:8082 --listen-addr=codsworth3:26357 --sql-addr=codsworth3:26259 --insecure --join=codsworth1:26357,codsworth2:26357,codsworth3:26357


networks:
  codsworthnet:
    driver: bridge

volumes:
  codsworth1:
  codsworth2:
  codsworth3:
